### ISSUE TITLE
Hello, i have this error what can i do ?

### ISSUE THREAD

**Issue by nhanb2004798** [badabing2005/PixelFlasher#137]
Opening Pif Manager ...
TB Checker option selected
2023-12-24 12:14:25 User Pressed Play Integrity API Checker.
bash arg: -p
bash arg: krypton.tbsafetychecker
bash arg: -c
bash arg: android.intent.category.LAUNCHER
bash arg: 1
args: [-p, krypton.tbsafetychecker, -c, android.intent.category.LAUNCHER, 1]
arg: "-p"
arg: "krypton.tbsafetychecker"
arg: "-c"
arg: "android.intent.category.LAUNCHER"
arg: "1"
data="krypton.tbsafetychecker"
data="android.intent.category.LAUNCHER"
Events injected: 1
## Network stats: elapsed time=59ms (0ms mobile, 0ms wifi, 59ms not connected)
2023-12-24 12:14:27 Getting coordinates for krypton.tbsafetychecker
uiautomator dump /data/local/tmp/pi.xml path on the device ...

2023-12-24 12:14:31 ERROR: uiautomator dump failed.
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at miui.content.res.ThemeCompatibilityLoader.getVersion(Unknown Source:11)
	at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(Unknown Source:2)
	at miui.content.res.ThemeCompatibilityLoader.loadConfig(Unknown Source:12)
	at miui.content.res.ThemeCompatibility.<clinit>(Unknown Source:40)
	at miui.content.res.ThemeCompatibility.isThemeEnabled(Unknown Source:0)
	at android.content.res.MiuiResourcesImpl.<clinit>(Unknown Source:0)
	at android.content.res.Resources.<init>(Unknown Source:20)
	at android.content.res.MiuiResources.<init>(Unknown Source:0)
	at android.content.res.Resources.getSystem(Unknown Source:9)
	at android.util.MiuiMultiWindowAdapter.<clinit>(Unknown Source:1)
	at android.util.MiuiMultiWindowAdapter.getSize(Unknown Source:0)
	at android.view.Display.getSize(Unknown Source:29)
	at com.android.commands.uiautomator.DumpCommand.run(DumpCommand.java:110)
	at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 19 more

Error: Could not get coordinates.

**Comment by badabing2005** [comment]
Curious what phone / OS are you on?
Unfortunately uiautomator (Google's work) which is used to drive these test is a bit buggy and does not work well on all devices.

**Comment by nhanb2004798** [comment]
im use mi 9t miui eu
im use test Play Integrity so it false

**Comment by badabing2005** [comment]
Unlock your device screen.
From a command shell please issue this command
```adb shell uiautomator dump /data/local/tmp/view.xml```
see if you get any errors.
If you don't I'm afraid you have a buggy uiautomator.

Only if you don't get any errors continue with the below.
Open up TB checker and run the same command again.
See if this time you get an error.
If you do, then uiautomator has issues dumping the TB Checker screen.
You can try with one of the other apps for testing to see if it works with the other apps.

uiautomator is used for two things.
1. Figuring out the coordinates of the button so that Pixelflasher can issue a command to tap on the button, but there are other ways to figure that out, and I can explain those if point 2 below works for you.
2. When the testing completes and the screen displays the results, uiautomator is used again to pull the screen dump and parse the contents so that PixelFlasher can display the results.

If you just want to invoke the testing, and check the results on the phone screen instead of your computer, you can do without uiautomator.

**Comment by nhanb2004798** [comment]
127|davinci:/ $ adb shell uiautomator dump /data/local/tmp/view.xml
/system/bin/sh: adb: inaccessible or not found

**Comment by badabing2005** [comment]
If you're already on the device, drop the adb shell part
just do `uiautomator dump /data/local/tmp/view.xml`

**Comment by nhanb2004798** [comment]
it show this
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:58)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(Unknown Source:11)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(Unknown Source:2)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(Unknown Source:12)
        at miui.content.res.ThemeCompatibility.<clinit>(Unknown Source:40)
        at miui.content.res.ThemeCompatibility.isThemeEnabled(Unknown Source:0)
        at android.content.res.MiuiResourcesImpl.<clinit>(Unknown Source:0)
        at android.content.res.Resources.<init>(Unknown Source:20)
        at android.content.res.MiuiResources.<init>(Unknown Source:0)
        at android.content.res.Resources.getSystem(Unknown Source:9)
        at android.util.MiuiMultiWindowAdapter.<clinit>(Unknown Source:1)
        at android.util.MiuiMultiWindowAdapter.getSize(Unknown Source:0)
        at android.view.Display.getSize(Unknown Source:29)
        at com.android.commands.uiautomator.DumpCommand.run(DumpCommand.java:110)
        at com.android.commands.uiautomator.Launcher.main(Launcher.java:83)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        ... 19 more
UI hierchary dumped to: /data/local/tmp/view.xml

**Comment by badabing2005** [comment]
Yeah, that's what I thought,
uiautomator is broken on your device.
I have one device like that.

**Comment by nhanb2004798** [comment]
what can i do now sir?

**Comment by badabing2005** [comment]
Go to developer setting.
Enable `Pointer Location` temporarily
Launch `TB Checker` Press and Hold on `Run Play Integrity Check`
Observe the x and y coordinates displayed
Take note of them.

In PixelFlasher's Help menu, select `Open PixelFlasher Working Directory`
See if you have a file named coord.json
If you do, edit it,
Otherwise create one.
The contents should be something like this.

```
{
    "DEVICE_ID": {
        "krypton.tbsafetychecker": "765 2298"
    }
}
```

replace DEVICE_ID with your device's id?
Adb devices should show you that, PF console also shows you when you select it.

Replace `765 2298` with the x and y values you took notes of.
Save

Test it out and see if it click on the right place, you can also enable show Taps to see where it is clicking.
If it works, you can undo the changes in developer options.

Keep in mind that it will give you an error when it tries to get the results, because that still requires uiautomator, however launching the app and tapping the test should work and you would see the results on the phone.

I'll add an option in the next version to skip getting the results if the option is selected.

**Comment by nhanb2004798** [comment]
i change id change x y but it still error and the phone not tap

**Comment by badabing2005** [comment]
what is the error?
did you enable the tap in developer options to see if it is tapping anywhere close to it?

**Comment by nhanb2004798** [comment]
I turn on it, and I don't see a tap anywhere on my phone's screen

**Comment by nhanb2004798** [comment]
uiautomator dump /data/local/tmp/pi.xml path on the device ...

2023-12-27 00:03:50 ERROR: uiautomator dump failed
it still error

**Comment by badabing2005** [comment]
please provide a support file

**Comment by nhanb2004798** [comment]
> 
[Uploading support_2023-12-27_01-08-24.zip…]()

**Comment by nhanb2004798** [comment]
[support_2023-12-27_01-08-24.zip](https://github.com/badabing2005/PixelFlasher/files/13773120/support_2023-12-27_01-08-24.zip)

**Comment by nhanb2004798** [comment]
which file?

**Comment by badabing2005** [comment]
generate a support file in PF, and submit the generated file.

**Comment by nhanb2004798** [comment]
[](url)
[support_2023-12-27_01-08-24.zip](https://github.com/badabing2005/PixelFlasher/files/13773166/support_2023-12-27_01-08-24.zip)

**Comment by badabing2005** [comment]
my bad, the filename is `coords.json` and not `coord.json` rename it and let me know.
if it still does not work, share the file but redact the device id.

**Comment by nhanb2004798** [comment]
[coords.json](https://github.com/badabing2005/PixelFlasher/files/13773189/coords.json)
not work

**Comment by badabing2005** [comment]
launch TB Checker and type this on the device shell
`input tap 534 1528`
and if you're doing it from PC
`adb shell input tap 534 1528`

see if it clicks the button
If it doesn't the coordinates are wrong.
If it does, please try again with PF (debug on) and then generate support file again please.

**Comment by nhanb2004798** [comment]
![image](https://github.com/badabing2005/PixelFlasher/assets/95465872/66fb4900-6a68-4ed4-8b56-9bc1a95cd8c6)

**Comment by badabing2005** [comment]
When you're on device you have to do it without adb shell part, see my previous post

**Comment by badabing2005** [comment]
Add an option to disable UIAutomator

**Comment by Yuq-q** [comment]
> launch TB Checker and type this on the device shell `input tap 534 1528` and if you're doing it from PC `adb shell input tap 534 1528`
> 
> see if it clicks the button If it doesn't the coordinates are wrong. If it does, please try again with PF (debug on) and then generate support file again please.

Sir, when I entered `adb shell input tap 568 1373`, the following error was reported. Do you have any clues about this?
<details>

```
PS C:\Users\HONOR\Desktop> adb shell input tap 568 1373
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createException(Unknown Source:36)
        at android.os.Parcel.readException(Unknown Source:11)
        at android.os.Parcel.readException(Unknown Source:10)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(Unknown Source:61)
        at android.hardware.input.InputManager.injectInputEvent(Unknown Source:21)
        at com.android.commands.input.Input.injectMotionEvent(Input.java:428)
        at com.android.commands.input.Input.access$200(Input.java:41)
        at com.android.commands.input.Input$InputTap.sendTap(Input.java:224)
        at com.android.commands.input.Input$InputTap.run(Input.java:218)
        at com.android.commands.input.Input.onRun(Input.java:108)
        at com.android.internal.os.BaseCommand.run(Unknown Source:24)
        at com.android.commands.input.Input.main(Input.java:71)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventInternal(Unknown Source:137)
        at com.android.server.input.InputManagerService.injectInputEvent(Unknown Source:0)
        at android.hardware.input.IInputManager$Stub.onTransact(Unknown Source:580)
        at android.os.Binder.execTransactInternal(Unknown Source:75)
        at android.os.Binder.execTransact(Unknown Source:16)
```
</details>

**Comment by Yuq-q** [comment]
> > launch TB Checker and type this on the device shell `input tap 534 1528` and if you're doing it from PC `adb shell input tap 534 1528`
> > see if it clicks the button If it doesn't the coordinates are wrong. If it does, please try again with PF (debug on) and then generate support file again please.
> 
> Sir, when I entered `adb shell input tap 568 1373`, the following error was reported. Do you have any clues about this?

> Keep in mind that it will give you an error when it tries to get the results, because that still requires uiautomator, however launching the app and tapping the test should work and you would see the results on the phone.

Not a big problem , I'll  manually tap it

**Comment by badabing2005** [comment]
Weird, it's the first time I see a permissions issue like this.
Try this command first to grant permissions and then try the tap command, see if it helps.

```
adb shell pm grant com.android.commands.input android.permission.INJECT_EVENTS
```

**Comment by Yuq-q** [comment]
> Weird, it's the first time I see a permissions issue like this. Try this command first to grant permissions and then try the tap command, see if it helps.
> 
> ```
> adb shell pm grant com.android.commands.input android.permission.INJECT_EVENTS
> ```

<details>

```
sirius:/ $ input tap 556 1359
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
        at android.os.Parcel.createException(Unknown Source:36)
        at android.os.Parcel.readException(Unknown Source:11)
        at android.os.Parcel.readException(Unknown Source:10)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(Unknown Source:61)
        at android.hardware.input.InputManager.injectInputEvent(Unknown Source:21)
        at com.android.commands.input.Input.injectMotionEvent(Input.java:428)
        at com.android.commands.input.Input.access$200(Input.java:41)
        at com.android.commands.input.Input$InputTap.sendTap(Input.java:224)
        at com.android.commands.input.Input$InputTap.run(Input.java:218)
        at com.android.commands.input.Input.onRun(Input.java:108)
        at com.android.internal.os.BaseCommand.run(Unknown Source:24)
        at com.android.commands.input.Input.main(Input.java:71)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(Unknown Source:24)
Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.input.InputManagerService.injectInputEventInternal(Unknown Source:137)
        at com.android.server.input.InputManagerService.injectInputEvent(Unknown Source:0)
        at android.hardware.input.IInputManager$Stub.onTransact(Unknown Source:580)
        at android.os.Binder.execTransactInternal(Unknown Source:75)
        at android.os.Binder.execTransact(Unknown Source:16)

1|sirius:/ $ pm grant com.android.commands.input android.permission.INJECT_EVENTS
Security exception: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.

java.lang.SecurityException: grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.
        at android.app.ContextImpl.enforce(Unknown Source:97)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Unknown Source:13)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(Unknown Source:47)
        at com.android.server.pm.permission.PermissionManagerService.access$1100(Unknown Source:0)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(Unknown Source:8)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(Unknown Source:31)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(Unknown Source:63)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(Unknown Source:920)
        at android.os.ShellCommand.exec(Unknown Source:55)
        at com.android.server.pm.PackageManagerService.onShellCommand(Unknown Source:12)
        at android.os.Binder.shellCommand(Unknown Source:0)
        at android.os.Binder.onTransact(Unknown Source:148)
        at android.content.pm.IPackageManager$Stub.onTransact(Unknown Source:21)
        at com.android.server.pm.PackageManagerService.onTransact(Unknown Source:0)
        at android.os.Binder.execTransactInternal(Unknown Source:75)
        at android.os.Binder.execTransact(Unknown Source:16)
```
</details>

[support_2024-01-21_12-31-09.zip](https://github.com/badabing2005/PixelFlasher/files/14000063/support_2024-01-21_12-31-09.zip)
