### ISSUE TITLE
 java.lang.SecurityException: Shell does not have permission to access user 11

### ISSUE THREAD

**Issue by Guneetgstar** [badabing2005/PixelFlasher#138]
PixelFlaser version: v6.4.2.0
OS: MacOS 12.5
Device: Pixel 7 Stock ROM
Root Access granted to shell: Yes
Feature: App Manager
ERROR: Could not get package list of all+uninstalled.
Console log:
```
Launching Package Manager ...

2023-12-24 20:08:21 ERROR: Could not get package list of all+uninstalled.
Return Code: 255.
Stdout: .
Stderr: 
Exception occurred while executing 'list':
java.lang.SecurityException: Shell does not have permission to access user 11
 com.android.server.am.ActivityManagerService.handleIncomingUser:13303 android.app.ActivityManager.handleIncomingUser:4745 com.android.server.pm.PackageManagerShellCommand.translateUserId:3678 
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:2468)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13303)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4745)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:3678)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:1040)
	at com.android.server.pm.PackageManagerShellCommand.runListPackages(PackageManagerShellCommand.java:936)
	at com.android.server.pm.PackageManagerShellCommand.runList(PackageManagerShellCommand.java:776)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:224)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6350)
	at android.os.Binder.shellCommand(Binder.java:1068)
	at android.os.Binder.onTransact(Binder.java:888)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4352)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6334)
	at android.os.Binder.execTransactInternal(Binder.java:1344)
	at android.os.Binder.execTransact(Binder.java:1275)
.
```
Sanitised support.zip: [support_2023-12-24_20-08-32.zip](https://github.com/badabing2005/PixelFlasher/files/13762130/support_2023-12-24_20-08-32.zip)

First of all thanks for providing such a feature packed tool.

FYI, I have a work profile installed on the device. Could this be the reason for the issue? I don't see anyone else reporting this issue. Is there any app I need to install on the device for this feature to work?

**Comment by badabing2005** [comment]
From the looks of it, it is related to work profile.
What do you get when you run the following command from terminal.
```
adb shell pm list packages -u
```

**Comment by Guneetgstar** [comment]
> adb shell pm list packages -u

Same error as shared in the logs. Any workaround?

**Comment by badabing2005** [comment]
This is a native command that PixelFlasher is executing.
If it is giving the same error, I'm afraid you'd have to bring it up with Google.

**Comment by Guneetgstar** [comment]
Or it's just the work profile policies not allowing the command to execute. Thanks for the quick response. I have been struggling with this since yesterday.
