### ISSUE TITLE
6.6.0.1-1 doesn't work on archlinux

### ISSUE THREAD

**Issue by LumenYoung** [badabing2005/PixelFlasher#145]
Dear maintainer of the PixelFlasher,

The current version of pixelflasher doesn't work on my laptop (Archlinux). My installation is from pixelflasher-bin(AUR package). The error is as following:

```
❯ PixelFlasher
global_args.config: None
config_file_path: /home/yang/.local/share/PixelFlasher/PixelFlasher.json
Loading configuration File ...
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1294, in request
  File "http/client.py", line 1340, in _send_request
  File "http/client.py", line 1289, in endheaders
  File "http/client.py", line 1048, in _send_output
  File "http/client.py", line 986, in send
  File "http/client.py", line 1466, in connect
  File "ssl.py", line 517, in wrap_socket
  File "ssl.py", line 1108, in _create
  File "ssl.py", line 1383, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wx/core.py", line 2346, in Notify
  File "wx/core.py", line 3552, in Notify
  File "Main.py", line 4297, in _show_main
  File "Main.py", line 350, in __init__
  File "Main.py", line 1335, in _build_menu_bar
  File "Main.py", line 188, in __init__
  File "Main.py", line 128, in __init__
  File "Main.py", line 149, in load_data
  File "runtime.py", line 2082, in get_google_images
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

```

I wonder if you can give me some insight on the reason of this failure to start the PixelFlasher?

Thank you for your awesome work.

**Comment by badabing2005** [comment]
Please try with version 6.6.1.0 and see if you still get this error.

**Comment by LumenYoung** [comment]
Thanks for your reply! This issue has been resolved and I'll close it with this comment. Thanks for your help.
