### ISSUE TITLE
Error on getting XiaomiPif - Version 6.6.1.0

### ISSUE THREAD

**Issue by aaroncoyco97** [badabing2005/PixelFlasher#148]
Hi guys, there's an exception when getting xiaomi pif.

2024-01-20 09:56:16 ERROR: Encountered an error in xiaomi_xml_to_json function
Traceback (most recent call last):
  File "runtime.py", line 2769, in xiaomi_xml_to_json
AttributeError: 'NoneType' object has no attribute 'iter'
Traceback (most recent call last):
  File "pif_manager.py", line 664, in XiaomiPif
TypeError: StyledTextCtrl.SetValue(): argument 1 has unexpected type 'NoneType'

**Comment by badabing2005** [comment]
I'm aware, and it's already fixed in the next that should be released soon.

**Comment by badabing2005** [comment]
Fixed in v6.6.7
