### ISSUE TITLE
HELP - ADB AppControl  re-installs leads to "data corruption" on rooted pixel 7 pro 

### ISSUE THREAD

**Issue by missionmankind** [badabing2005/PixelFlasher#154]
So i have a pixel 7 pro. its running Android 13 security patch May 2023. Im rooted with Magisk and LSPosed installed. Safetynet was installed too and i had a small deny list going on 4 google apps and a coupe games. 
I been having issues with my US Mobile hotspot not working. I thought of installing some previously debloated apps on ADB AppControl v1.8.3.
I reinstalled a couple verizon apps (carrier services) another com.verizon app. i didnt realize it but these apps conflicted with already installed apps handling my phone carrier and provisional settings on US Mobile. Suddenly my phone shut off and rebooted to a “Can’t load Android System Your data may be corrupt” error. 
I tried flashing a factory image with Pixel Flasher but it kept aborting with this error below.

**==============================================================================
2024-02-05 02:13:12 User initiated Process firmware
==============================================================================

==============================================================================
2024-02-05 02:13:12 PixelFlasher 6.7.1.0 Processing firmware file ...
==============================================================================
Low memory option: False
Available Free Memory: 1.44 GB / 5.90 GB
Factory File: C:\Users\PWNing YOU softly\Desktop\cheetah-tq2a.230505.002-factory-fe44ced0.zip
Failed to check_zip_contains_file_fast. Reason:
Traceback (most recent call last):
File "runtime.py", line 1330, in check_zip_contains_file_fast
File "zipfile.py", line 941, in read
File "zipfile.py", line 1025, in _read1
File "zipfile.py", line 1055, in _read2
File "zipfile.py", line 775, in read
MemoryError
Failed to check_zip_contains_file_fast. Reason:
Traceback (most recent call last):
File "runtime.py", line 1330, in check_zip_contains_file_fast
File "zipfile.py", line 941, in read
File "zipfile.py", line 1025, in _read1
File "zipfile.py", line 1055, in _read2
File "zipfile.py", line 775, in read
MemoryError
Failed to check_zip_contains_file_fast. Reason:
Traceback (most recent call last):
File "runtime.py", line 1330, in check_zip_contains_file_fast
File "zipfile.py", line 941, in read
File "zipfile.py", line 1025, in _read1
File "zipfile.py", line 1055, in _read2
File "zipfile.py", line 775, in read
MemoryError
Detected Pixel firmware
7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
Scanning the drive for archives:
1 file, 2750491221 bytes (2624 MiB)
Extracting archive: C:\Users\PWNing YOU softly\Desktop\cheetah-tq2a.230505.002-factory-fe44ced0.zip
--
Path = C:\Users\PWNing YOU softly\Desktop\cheetah-tq2a.230505.002-factory-fe44ced0.zip
Type = zip
Physical Size = 2750491221
Everything is Ok
Folders: **1**
Files: 6
Size: 2767090478
Compressed: 2750491221
Nothing to extract from firmware
Aborting ...**

So do i need a smaller init.boot file? im trying tp save my data and so far update via ADB keeps failing. Im trying to keep data. I just have no idea what mode my phone has to be in while flasing factory vs OTA. I sure could use some help.
thank you very much.

-Jake

**Comment by badabing2005** [comment]
You reported this in PixelFlasher support thread on XDA and I responded to you [there](https://xdaforums.com/t/guide-january-3-2024-root-pixel-7-pro-unlock-bootloader-pass-safetynet-both-slots-bootable-more.4505353/post-89320099).

You repeated the question again without providing any of the stuff I requested.
And yet again you're asking the same thing here, and again without providing any of the details I requested nor the support file.

**Comment by missionmankind** [comment]
I just located the apps installed, it was the following according to my history folder on my fesktop...
I cannot tell you specifically which ones I enabled or installed. I think I possibly enabled Verizon apps and installed the sim toolkit and manager.

-com.verizon.IIKagent [v.13]

-My Verizon Services com.verizon.mips.services [v1.0.178.5 ]

-sim toolkit com.android.stk [v.13]

-sim manager com.google.android.euicc [v.D.2.1.510475198-google]


the color scheme of the G logo on boot usually shows up as this orange color corresponding to my theme I had set with orange accents. Now it's booting up with like a blue pink G logom I noticed this right away. It did this as soon as it crashed and rebooted the first time and stayed booting with that Google logo that pops up before your lockscteen. This means some change was done to the theme without me doing anything. installing cellular related apps caused this I know it did. I think this is the least of my worries (a new color of Google logo) but might be a hint possibly.

your next question is I don't have enough memory. well that's impossible I have on my used a small portion of 128gb storage. 
I don't know what that error is.
I know I'm rooted. Maybe it's a smaller partiton. I have no clue. That is extremely puzzling. 

I cannot figure out how to create a support file in pixel flasher. I thought you meant start a support ticket on GitHub. my bad.
I'm not that experienced. Please forgive me.

**Comment by badabing2005** [comment]
> your next question is I don't have enough memory. well that's impossible I have on my used a small portion of 128gb storage.
I don't know what that error is.

128GB is not memory, and we're not talking about your phone here, you're running PixelFlasher on your computer, and it's your computer's memory that is low.

This is from your post above
**Available Free Memory: 1.44 GB / 5.90 GB**

> I know I'm rooted. Maybe it's a smaller partiton. I have no clue. That is extremely puzzling.
Probably because you haven't read the Readme here or the OP at XDA to know how to use the program.

> I cannot figure out how to create a support file in pixel flasher. I thought you meant start a support ticket on GitHub. my bad.
Again it's in the readme, and thread OP at XDA, hint: Troubleshooting.

> I'm not that experienced. Please forgive me.
Fail enough, but you know how to read, do that.

Connect your phone to your PC , run PixelFlasher, hit the scan button, and then generate a support file and provide that please.

You keep on saying you don't know what mode the phone needs to be in, that's exactly why I'm asking you to get a support file.
PixelFlasher can detect the mode and adapt, I need to understand the state of your phone before I can propose any steps to remedy the issue.

**Comment by missionmankind** [comment]
ok ill try that. i do appreciate the help. ill post back here asap.

**Comment by missionmankind** [comment]
here is the finished scan:

PixelFlasher 6.7.1.0 started on :2024-02-05 21:16:26
Platform: win32
System Timezone: ('Central Standard Time', 'Central Daylight Time') Offset: -6.0
Configuration Folder Path: C:\Users\PWNing YOU softly\AppData\Roaming\PixelFlasher
Configuration File Path: C:\Users\PWNing YOU softly\AppData\Roaming\PixelFlasher\PixelFlasher.json
{
    "advanced_options": false,
    "boot_id": null,
    "check_for_bootloader_unlocked": true,
    "check_for_disk_space": true,
    "check_for_firmware_hash_validity": true,
    "create_boot_tar": false,
    "custom_codepage": null,
    "custom_rom": false,
    "custom_rom_path": null,
    "customize_font": false,
    "delete_bundled_libs": "",
    "dev_mode": false,
    "device": "28081FDH300A58",
    "disable_verification": false,
    "disable_verity": false,
    "enable_bulk_prop": false,
    "enable_dg_clean": false,
    "enable_pixel_img_process": false,
    "extra_img_extracts": false,
    "fastboot_force": false,
    "fastboot_verbose": false,
    "firmware_has_init_boot": false,
    "firmware_is_ota": false,
    "firmware_path": "C:\\Users\\PWNing YOU softly\\Desktop\\platform-tools\\backup & flashing\\factory init_boot & safetynet fix\\cheetah-tq2a.230505.002-factory-fe44ced0.zip",
    "firmware_sha256": "fe44ced0de116faaabf4928ee3db7f382d034d54fe5da7dab7575ba4febd9a89",
    "first_run_date": null,
    "flash_both_slots": false,
    "flash_to_inactive_slot": false,
    "force_codepage": false,
    "google_images_last_checked": 1707117145,
    "google_images_update_frequency": 1,
    "height": 786,
    "last_run_date": "2024-02-05 18:42:49",
    "linux_file_explorer": "",
    "linux_shell": "",
    "low_mem": false,
    "magisk": "com.topjohnwu.magisk",
    "magisk_height": 790,
    "magisk_width": 1388,
    "mode": "keepData",
    "no_reboot": false,
    "offer_patch_methods": false,
    "pf_font_face": "Courier",
    "pf_font_size": 12,
    "pf_home": null,
    "phone_path": "/storage/emulated/0/Download",
    "pif": {
        "auto_check_play_integrity": false,
        "auto_fill": false,
        "auto_update_pif_json": false,
        "disable_uiautomator": false,
        "first_api_value_when_forced": "25",
        "force_first_api": false,
        "keep_unknown": true,
        "sort_keys": true,
        "test_app_index": 0
    },
    "pif_height": 790,
    "pif_width": 1245,
    "platform_tools_path": "C:\\Program Files\\platform-tools",
    "pos_x": -9,
    "pos_y": -9,
    "rom_has_init_boot": false,
    "rom_sha256": null,
    "scrcpy": {
        "flags": "",
        "path": ""
    },
    "selected_boot_md5": null,
    "show_notifications": false,
    "show_recovery_patching_option": false,
    "temporary_root": false,
    "toolbar": {
        "tb_position": "top",
        "tb_show_icons": true,
        "tb_show_text": true,
        "visible": {
            "adb_shell": true,
            "configuration": false,
            "device_info": true,
            "install_apk": true,
            "install_magisk": true,
            "lock_bootloader": true,
            "magisk_backup_manager": true,
            "magisk_modules": true,
            "package_manager": true,
            "partition_manager": true,
            "pif_manager": true,
            "reboot_bootloader": true,
            "reboot_download": true,
            "reboot_fastbootd": true,
            "reboot_recovery": true,
            "reboot_safe_mode": true,
            "reboot_sideload": true,
            "reboot_system": true,
            "scrcpy": true,
            "sos": true,
            "switch_slot": true,
            "unlock_bootloader": true
        }
    },
    "update_check": true,
    "use_busybox_shell": false,
    "verbose": false,
    "version": "6.7.1.0",
    "width": 1306
}
System Default Encoding: utf-8
File System Encoding:    utf-8
Active code page: 437
Bundle Directory: C:\Users\PWNING~1\AppData\Local\Temp\_MEI37802
Available Free Memory: 2.30 GB / 5.90 GB
Available Free Disk on system drive: 439 GB
Available Free Disk on PixelFlasher data drive: 439 GB

Using previously stored firmware SHA-256 ...
Firmware SHA-256: fe44ced0de116faaabf4928ee3db7f382d034d54fe5da7dab7575ba4febd9a89
Expected to match fe44ced0 in the firmware filename and did. This is good!

2024-02-05 21:16:26 Selected Platform Tools Path:
C:\Program Files\platform-tools.
SDK Version:      34.0.5-10900879
Adb SHA256:       58765259a349cce392fbb2f15dab75fed3b7c0b40cc68a7653278b9850602a2f
Fastboot SHA256:  43703d6e235a72837c6385a440091dc5da6f522d86cf7735ed53c2a508e2b06b

Please Process the firmware!

Loading Device list ...
This could take a while, please be patient.

Discovered 0 device(s) connected.
2024-02-05 21:16:26 No Device is selected!
Load time: 2 seconds

==============================================================================
 2024-02-05 21:17:22 User initiated Scan
==============================================================================

2024-02-05 21:17:22 Scanning for Devices ...
1 Device(s) are found.
2024-02-05 21:17:22 No Device is selected!

**Comment by badabing2005** [comment]
That's not a support file, if you're not going to create a support file, I'm going to close this.
By the way, I'm offering my help here. There is no issue with PixelFlasher related to your case.

**Comment by missionmankind** [comment]
sorry i just relized thats pixel flasher. i am trying to set my phone up to scan it.

**Comment by missionmankind** [comment]
i finally found it in help menu. im linking the rar file here.
[support_2024-02-05_21-28-40.zip](https://github.com/badabing2005/PixelFlasher/files/14174331/support_2024-02-05_21-28-40.zip)

**Comment by missionmankind** [comment]
Please let me know if i should first attempt a flash, then create a support file. im just trying to cover bases. I hope that was the correct file. Thank you for helping. this is very important and im giving it my best shot. Please excuse my ignorance.

**Comment by missionmankind** [comment]
Thanks for this. So I'm getting to the part where you select boot file. I read the OP too and cannot figure this step out. The instructions are there but doing this on the GUI is another understanding i dont have and most people havent been too helpful, rather they see me as a noob so i can never get past this.
Frustrated, I just try to flash pixel phone and it's saying device firmware mismatch.
I downloaded 2 different images now (May 2023 security patch OTA which is what my phone has, and I tried a June 2023 OTA, both are giving firmware mismatch. 
I'm extremely thankful and honored to have your help. I just don't know what selecting boot file is or means on the GUI of Pixel Flasher. I sat up till 3am trying to figure this out. Cant find any videos on it, OP thread says the same. Select boot file. So i can only see a folder icon (init.boot in my case for Pixel 7 Pro), i select it and it's saying "disk image file is corrupted". So i skipped that after hours of frustration.
I tried flashing, and it gives this device firmware mismatch warning. I have no idea why its saying that when It's for my device. So i flash pixel phone, it finished with result 0 and now I can't get into recovery mode. 
I can get to fast boot but not recovery. It boots this message now. But i can still get it to boot fast boot to select different modes.

At this point, i pretty much know the phone is bricked and its my fault.

![IMG_20240207_110332](https://github.com/badabing2005/PixelFlasher/assets/77211748/5b2ec91e-a5a1-4387-8112-9289079a7953)

**Comment by badabing2005** [comment]
No your phone is not bricked.
Selecting boot is detailed in [Basic Usage](https://github.com/badabing2005/PixelFlasher#basic-mode), step 6, those numbers are where you click.

Device mismatch can happen if your device is in recovery mode and the model cannot be read, however it should not happen with bootloader mode or adb mode.

Everytime you do something, you need to provide a support file for me to analyze and provide further instructions.

**Comment by badabing2005** [comment]
This issue was automatically closed by Github bot, due to inactivity.
