### ISSUE TITLE
Crashed when flashing on Mac OS

### ISSUE THREAD

**Issue by hcbille** [badabing2005/PixelFlasher#188]
Got this error when flashing full OTA on a Pixel 7a

> `❌ 2024-04-08 10:29:28 ERROR: Encountered an error while flashing
Traceback (most recent call last):
  File "Main.py", line 4214, in _on_flash
  File "modules.py", line 4174, in flash_phone
  File "modules.py", line 4065, in reboot_device_to_bootloader
AttributeError: 'NoneType' object has no attribute 'reboot_bootloader'
`

**Comment by badabing2005** [comment]
Sorry, without support file, I can't guess what happened.
