### ISSUE TITLE
Fails to flash APatch with `AttributeError: 'NoneType' object has no attribute 'hardware'`

### ISSUE THREAD

**Issue by drewbitt** [badabing2005/PixelFlasher#221]
PixelFlasher version 7
```
=======================================
Selected Device on 2024-07-13 16:08:38:
=======================================
    Device ID:                       37291FDJG00F5G
    Device Model:                    husky
    Device Active Slot:              b
    Device Mode:                     f.b
    Device Name:                     Pixel 8 Pro
    Device First API Level:          34
    Device Version End Date:         October 2030
    Device Security Update End Date: October 2030
    Has init_boot partition:         True
    Device Bootloader Version:       ripcurrent-14.5-11693900
    Device Unlocked:                 True
    slot-retry-count:a:              
    slot-unbootable:a:               
    slot-successful:a:               
    slot-retry-count:b:              
    slot-unbootable:b:               
    slot-successful:b:               


2024-07-13 16:08:38 Getting device: 37291FDJG00F5G state  ...
Rebooting device: 37291FDJG00F5G to bootloader ...
Fastboot waiting for device: 37291FDJG00F5G for bootloader ...
device: 37291FDJG00F5G is now in bootloader mode.
Updating connected devices ...
Checking if the bootloader is unlocked ...
Bootloader is unlocked, continuing ...

❌ 2024-07-13 16:08:39 ERROR: Encountered an error while flashing
Traceback (most recent call last):
  File "Main.py", line 4484, in _on_flash
  File "modules.py", line 4534, in flash_phone
  File "modules.py", line 4187, in apply_patch_if_needed
AttributeError: 'NoneType' object has no attribute 'hardware'
```

[support_2024-07-13_16-09-47.zip](https://github.com/user-attachments/files/16203554/support_2024-07-13_16-09-47.zip)

**Comment by drewbitt** [comment]
I just tried it again, and it worked. So there is some scenario where it cannot get that key

**Comment by badabing2005** [comment]
You were already on the correct firmware, so you didn't need to flash the whole firmware, you could have just chosen the patched file and selected `Flash Boot` instead or `Flash Pixel Phone` (in 7.1 `Flash Pixel Phone` is renamed to `Flash Device`)

Regardless there is a minor bug not accounting for device.hardware being None (which happens to be the case when the phone is in bootloader mode)

I'll have it handled in the next release.
Thanks for the ticket.

**Comment by drewbitt** [comment]
Thanks. Was not aware of that feature.

**Comment by badabing2005** [comment]
Fixed: https://github.com/badabing2005/PixelFlasher/releases/tag/v7.1.1.0
