### ISSUE TITLE
ModuleNotFoundError: No module named 'darkdetect'

### ISSUE THREAD

**Issue by garyemiller** [badabing2005/PixelFlasher#29]
I just git cloned this repo.  Then:

```
# python PixelFlasher.py
Traceback (most recent call last):
  File "/usr/local/src/Android/PixelFlasher/PixelFlasher.py", line 3, in <module>
    import Main
  File "/usr/local/src/Android/PixelFlasher/Main.py", line 15, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```

Gnetoo knows of no such modules:

``` 
# eix darkdetect
No matches found
```
 Where do I get it?

**Comment by badabing2005** [comment]
May I ask which PixelFlasher build are you using?
I suppose you are using the Linux one?
Can you try the Kali build and report back please.

darkdetect is in the Python module [requirements.txt](https://github.com/badabing2005/PixelFlasher/blob/f342fd70b2cd860162bb8ee44c044f40b9b3abb9/requirements.txt#L7)
And as you can [see](https://github.com/badabing2005/PixelFlasher/actions/runs/3194236274/jobs/5213609295#step:9:51) version 0.7.1 is downloaded during the build.

It behooves me as to why it's not found, but this isn't the only issue with building it on Ubuntu.
See #21, #23

**Comment by garyemiller** [comment]
> May I ask which PixelFlasher build are you using? 

git cloned from this repo.

>  Can you try the Kali build and report back please.

What is "kali"?

> And as you can see version 0.7.1 is downloaded during the build.

What build?

The install directions at the top of the README.md seemed clear, no build:

```
Installation

PixelFlasher doesn't have to be installed, just double-click it and it'll start.

```

I stopped reading the README.md right there.

> this isn't the only issue with building it on Ubuntu.

I'm not using Ubuntu, I'm using Gentoo.

**Comment by garyemiller** [comment]
> I tried to give full details

Maybe they seemed complete to you, but not me.

When the doc, at the top, says all I need to do is run the program, what else would you expect me to do?

> No one claimed that you were running on Ubuntu.

And yet you keep asking me to run something built on Ubuntu?  Very little built on Ubuntu runs on non-Ubuntu derived distributions.

So humor you, I tried it, no joy:

```
/var/tmp $ chmod 755 PixelFlasher_Kali 
/var/tmp $ ./PixelFlasher_Kali 
Traceback (most recent call last):
  File "PixelFlasher.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "Main.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: libnsl.so.2: cannot open shared object file: No such file or directory
[31315] Failed to execute script 'PixelFlasher' due to unhandled exception!
```

**Comment by garyemiller** [comment]
PixelFlasher-Linux seems to start, with warnings:

```
/var/tmp $ chmod 755 PixelFlasher-Linux 
/var/tmp $ ./PixelFlasher-Linux 
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Loading configuration File ...

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:02:15.766: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

I'll give that a try.

**Comment by garyemiller** [comment]
A ton of warnings:

```
/var/tmp # ./PixelFlasher-Linux 
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Loading configuration File ...

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:02:15.766: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.560: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.560: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.560: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.560: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.560: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.560: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.560: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.560: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.562: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.562: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.562: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.562: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.562: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.562: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.562: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.562: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.564: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.564: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.564: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.564: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.564: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:08.564: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:08.564: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:08.564: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.577: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.577: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.577: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.577: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.577: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.577: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.577: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.577: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.579: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.579: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.579: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.579: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.579: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.579: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.579: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.579: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.582: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.582: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.582: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.582: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.582: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.582: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.582: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.582: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.601: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.601: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.601: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.602: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.602: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:09.602: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:09.602: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:09.602: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.186: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.186: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.186: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.186: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.187: Error loading theme icon 'help-about' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/help-about.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.187: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.187: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.187: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.197: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.198: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.198: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.198: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.198: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.198: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.198: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.198: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.732: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.732: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.732: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.732: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.732: Error loading theme icon 'application-exit' for stock: Failed to load /usr/share/icons/Adwaita/16x16/legacy/application-exit.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gtk-WARNING **: 14:06:10.733: Error loading theme icon 'image-missing' for stock: Failed to load /usr/share/icons/Adwaita/16x16/status/image-missing.png: Unrecognized image file format

(PixelFlasher-Linux:31479): Gdk-CRITICAL **: 14:06:10.733: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(PixelFlasher-Linux:31479): GLib-GObject-CRITICAL **: 14:06:10.733: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by badabing2005** [comment]
> Maybe they seemed complete to you, but not me.
> When the doc, at the top, says all I need to do is run the program, what else would you expect me to do?

Yes, all you need to do is run the program, however as you experienced and reported, it didn't work on Gentoo, hence why I suggested that you give another build a try,

> And yet you keep asking me to run something built on Ubuntu? Very little built on Ubuntu runs on non-Ubuntu derived distributions.

In fact I asked you to try the Kali build not the Ubuntu.
Most people that have tried the Kali build, they had success, even tough their platform is not Kali, you can check the tickets referenced earlier.

I'm sorry that you're running into problems and that even Kali build did not work for you, although Python is cross platform (or supposed to be), most libraries including GUI Python (in this case WxPython) is platform specific, and need to be build per platform or a pre-built wheel needs to be available.
Building these are not straight forward, and they depend on GTK which varies on each platform, not only that I would need to have a setup for each platform.

After endless days of effort, I managed to get Ubuntu builds running on Github workflows, which is the build labelled `PixelFlasher_Linux`
Unfortunately that seems to only work on Ubuntu and few Debian based Linux flavors.
I have a Kali setup, which I use to build the Kali version, which luckily happens to work for majority of the Linux flavors.
I build the MacOSX in a docker container.

Setting each of these requires hardware resources, time and knowledge.
The best I can suggest is if Kali version is not working for you, try building it yourself, see 
[Build it yourself section](https://github.com/badabing2005/PixelFlasher#build-it-yourself)
If it works for you, great, if not, then I'll keep this ticket open, hopefully eventually I'll have some free time to take a stab at it.

**Comment by badabing2005** [comment]
@garyemiller 
Please try [this build](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.4.0.0-alpha) and see if it solves your issue.

**Comment by garyemiller** [comment]
> @garyemiller Please try [this build](https://github.com/badabing2005/PixelFlasher/releases/tag/v4.4.0.0-alpha) and see if it solves your issue.

What kind of file has the extension  "04"?

Oh, it is a binary.   It seems to run, lots of warnings:

```
Loading configuration File ...

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.634: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.634: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.634: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.634: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): GLib-GObject-WARNING **: 14:22:32.635: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(PixelFlasher-Ubuntu-22.04:25030): Gtk-CRITICAL **: 14:22:32.635: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(PixelFlasher-Ubuntu-22.04:25030): Gtk-WARNING **: 14:22:32.640: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
PixelFlasher-Ubuntu-22.04
```

I tried to find my device by pressing the scan button. 

```

Load time: 2 seconds

2022-11-28 14:25:12 Scanning for Devices ...
No Devices found.
2022-11-28 14:25:12 No Device is selected!

2022-11-28 14:26:21 Scanning for Devices ...
1 Device(s) are found.
2022-11-28 14:26:34 No Device is selected!
```

But command line adb is fine:

```

dilbert ~ # adb version
Android Debug Bridge version 1.0.41
Version 33.0.3-android-tools
Installed as /usr/bin/adb

dilbert ~ # adb devices
List of devices attached
27131JEGR43159	device

```

**Comment by garyemiller** [comment]
Oh, I then had to select from a drop down that does not look like a drop down.  Got the device selected.

**Comment by garyemiller** [comment]
Good so far, now I gotta figure out how to use it...

**Comment by garyemiller** [comment]
I have a high dpi screen, and poor eyesight.  So I made the font bigger, and get these errors:

```

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

**Comment by badabing2005** [comment]
Aside from those errors, is it still usable?
Unfortunately non of these error are PixelFlasher errors.
PixelFlasher is written in Python, and for UI components, WxPython is used.
WxPython uses GTK libraries, and these errors are errors in GTK library.
If you Google for this error, you'd see there are so many of these.

As for Usage, see the Readme in the main page.

**Comment by garyemiller** [comment]
Seems to me the "invalid rectangle" is not a WxPython error.  It usually comes from putting variable sized text in fixed sized boxes.  I have often made that mistake.

> Aside from those errors, is it still usable?

So far, so good.  It will take me a few days to play with it.  I need to do a Pixel update, and that will be a good test.

**Comment by badabing2005** [comment]
> Seems to me the "invalid rectangle" is not a WxPython error. It usually comes from putting variable sized text in fixed sized boxes. I have often made that mistake.

The thing the boxes as you say are dynamic, they are supposed to self adjust
Perhaps a screenshot would be helpful, I can see if anything is falling out of boundaries.

See I set a large font to show,
![image](https://user-images.githubusercontent.com/22603312/204411687-91e104ed-db89-41b9-89b7-60a904d5c313.png)

![image](https://user-images.githubusercontent.com/22603312/204411743-28147a71-2c26-4327-b712-559a9da6b7df.png)

By the font selection only applies to Monospaced font used in the app, the others are all system default.


> So far, so good. It will take me a few days to play with it. I need to do a Pixel update, and that will be a good test.

No worries, take your time.

**Comment by badabing2005** [comment]
@garyemiller 
Are you still having issues with 4.6.1 ?

**Comment by badabing2005** [comment]
Closing the issue, no response, and it is most likely fixed with the latest builds.
