### ISSUE TITLE
Failed to process firmware zip: UnboundLocalError: local variable 'files_to_extract' referenced before assignment

### ISSUE THREAD

**Issue by blueset** [badabing2005/PixelFlasher#30]
The following error has occurred when processing firmware zip file:

```
==============================================================================
 2022-10-15 18:44:56 PixelFlasher 4.3.0.0         Processing firmware file ...
==============================================================================
7-Zip (z) 21.07 (x64) : Copyright (c) 1999-2021 Igor Pavlov : 2021-12-26
64-bit locale=en_US.UTF-8 Threads:16
Scanning the drive for archives:
1 file, 2510199318 bytes (2394 MiB)
Extracting archive: /Users/blueset/Downloads/raven-tp1a.221005.002-factory-d61dff29.zip
--
Path = /Users/blueset/Downloads/raven-tp1a.221005.002-factory-d61dff29.zip
Type = zip
Physical Size = 2510199318
Everything is Ok
Folders: 1
Files: 6
Size:       2528194928
Compressed: 2510199318
Traceback (most recent call last):
  File "Main.py", line 850, in _on_process_firmware
  File "modules.py", line 648, in process_file
UnboundLocalError: local variable 'files_to_extract' referenced before assignment
```

Version info: 

```
PixelFlasher 4.3.0.0 started on 2022-10-15 18:41:57
Platform: darwin
Configuration Path: /Users/blueset/Library/Application Support/PixelFlasher
null
System Default Encoding: utf-8
File System Encoding:    utf-8

2022-10-15 18:41:57 Selected Platform Tools Path:
/usr/local/bin.
SDK Version: 33.0.3-8952118
```

**Comment by badabing2005** [comment]
Thanks for reporting it, a silly oversight, fixed.
