### ISSUE TITLE
Error due opening console

### ISSUE THREAD

**Issue by Gokujo** [badabing2005/PixelFlasher#78]
I am using Ubuntu 22.04 and I tried to open shell and got this error:

```
Please select a boot image!
Opening an adb shell command for device: 22221FDEE001Y5 ...
Traceback (most recent call last):
  File "Main.py", line 1800, in _on_adb_shell
  File "phone.py", line 1990, in open_shell
AttributeError: module 'subprocess' has no attribute 'CREATE_NEW_CONSOLE'
```

**Comment by badabing2005** [comment]
OK thanks, I'll look into this and try to get it fixed in the next release
